### ISSUE TITLE
Replace partially working. Not replacing all variables 

### ISSUE THREAD

**Issue by sagun786** [datamonsters/replace-action#3]
Help
1. Issue: $LOCALE_CODE, $LOCALE_PROP and $LOCALE_NAME gets replaced checked using server logs but $DEV_SQUIDEX_CLIENT_ID and $DEV_SQUIDEX_CLIENT_SECRET don't get replaced (as per server logs but in Github action workflow logs is shows '***' as replaced
2. Goal: Want to replace config environment variables for deployments in Github Action Workflow

```
steps:
      
      - uses: actions/checkout@v1  
      - name: Desktop Build replace-action LOCALE VARIABLES
        uses: datamonsters/replace-action@v2
        with: 
          files: ./projects/ql-app-desktop/src/environments/environment.dynamic.ts
          replacements: '$LOCALE_CODE=${{ secrets.ZH_HK_LOCALE_CODE }},$LOCALE_PROP=${{ secrets.ZH_HK_LOCALE_PROP }},$LOCALE_NAME=${{ secrets.ZH_HK_LOCALE_NAME }}'
      - name: Mobile Build replace-action LOCALE VARIABLES 
        uses: datamonsters/replace-action@v2
        with: 
          files: ./projects/ql-app-mobile/src/environments/environment.dynamic.ts
          replacements: '$LOCALE_CODE=${{ secrets.ZH_HK_LOCALE_CODE }},$LOCALE_PROP=${{ secrets.ZH_HK_LOCALE_PROP }},$LOCALE_NAME=${{ secrets.ZH_HK_LOCALE_NAME }}'
      - name: Desktop Build replace-action SQUIDEX SECRETS
        uses: datamonsters/replace-action@v2
        with: 
          files: ./projects/ql-app-desktop/src/environments/environment.dynamic.ts
          replacements: '$DEV_SQUIDEX_CLIENT_ID=${{ secrets.DEV_SQUIDEX_CLIENT_ID }},$DEV_SQUIDEX_CLIENT_SECRET=${{ secrets.DEV_SQUIDEX_CLIENT_SECRET }}'
      - name: Mobile Build replace-action SQUIDEX SECRETS
        uses: datamonsters/replace-action@v2
        with: 
          files: ./projects/ql-app-mobile/src/environments/environment.dynamic.ts
          replacements: '$DEV_SQUIDEX_CLIENT_ID=${{ secrets.DEV_SQUIDEX_CLIENT_ID }},$DEV_SQUIDEX_CLIENT_SECRET=${{ secrets.DEV_SQUIDEX_CLIENT_SECRET }}'
```
